### ISSUE TITLE
TODO List for the v1.0 release

### ISSUE THREAD

**Issue by roccomuso** [roccomuso/asteroids-multiplayer#1]
## Game
- [x] Player remaining healthBar on Screen.
- [ ] On screen score points.

## Multiplayer
- [ ] Basic multiplayer (socket.io).
- [ ] Connected users window.
- [ ] Pseudo-random spawn of asteroids and planets.

## Animations
- [ ] Ships destruction Animation.
- [ ] Ships destruction Sound.
- [ ] Asteroids destruction Animation.
- [ ] Planets destruction Animation.

## Sounds
- [ ] Ships destruction sound.
- [ ] Asteroid destruction sound.
- [ ] Ship & Asteroid collision sound.
- [ ] Bullet & Asteroid collision sound (needs to be changed)

## Music
- [ ] Soundtrack required.

## Menu
- [ ] Basic in-game Menù.
